apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: n8n
          image: n8nio/n8n:2.2.4
          ports:
            - containerPort: 5678
              name: http
          env:
            # IMPORTANT: avoid K8s service env collision + ensure numeric
            - name: N8N_PORT
              value: "5678"
            - name: N8N_HOST
              value: "0.0.0.0"
            - name: N8N_METRICS
              value: "true"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: data
              mountPath: /home/node/.n8n
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: n8n-data
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-svc
  namespace: aiops
  labels:
    app: n8n
spec:
  selector:
    app: n8n
  ports:
    - name: http
      port: 5678
      targetPort: http
  type: ClusterIP
